version: "2.0"
services:
  app:
    build: ./frontend
    networks:
      - backend
    ports:
      - 3000:3000
    depends_on:
      - server
    env_file:
      - ./env-list
  server:
    build: ./backend
    networks:
      - backend
    ports:
      - 8080:3000
    depends_on:
      - mongodb
    env_file:
      - ./env-list

networks:
  backend:
    name: backend
    driver: bridge

